name: Tests

on:
  push:
    branches:
      - main
      - 1.x
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - python-version: "3.11"
            os: ubuntu-latest
          - python-version: "3.12"
            os: windows-latest
          - python-version: "3.13"
            os: ubuntu-latest
          - python-version: "3.14"
            os: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install stack-to-chunk
        if: ${{ matrix.python-version != '3.11' }}
        run: uv sync --dev

      - name: Install stack-to-chunk with lowest dependencies
        if: ${{ matrix.python-version == '3.11' }}
        run: uv sync --dev --resolution lowest

      - name: Run tests
        run: uv run pytest

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
